changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: Release 💎
      labels:
        - "💎release"
    - title: New Features 🎉
      labels:
        - "🌟feature"
    - title: Fix 🛠️
      labels:
        - "🛠️fix"
    - title: Refactoring ♻️
      labels:
        - "♻refactor"
    - title: Bug Fix 🕷️
      labels:
        - "🕷️bug"
    - title: Other Changes 🛠
      labels:
        - "*"
