name: 🛠️新規タスク
description: 誤字脱字の修正や、機能面の細かい修正などはこちら
title: "[Fix]: "
labels: ["🛠️fix"]
body:
  - type: markdown
    attributes:
      value: |
        この機能の開発を始める際、`fix/#Issue番号_作業名` でブランチを切ってください。
  - type: textarea
    id: purpose
    attributes:
      label: 目的
      description: このIssueの目的を記入してください。
      placeholder:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        以下、オプションです。よろしければご記入ください。
  - type: textarea
    id: task_list
    attributes:
      label: タスクリスト
      description: このタスクの達成に必要な作業を具体的に列挙してください。
      value: |
        - [ ] TBD…
    validations:
      required: false
  - type: textarea
    id: reference
    attributes:
      label: 参考
      description: 関連する資料やIssueがあれば教えてください。
    validations:
      required: false
  - type: textarea
    id: notice
    attributes:
      label: 留意事項
    validations:
      required: false
  - type: textarea
    id: consideration
    attributes:
      label: 検討事項
    validations:
      required: false

