name: "Closeしたタイミングでラベルを削除"

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]
jobs:
  remove_priority_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            🔥emergency
            ⏳low_priority
            👀needs_review
            🧑🏻‍🎓needs_investigation
            🚧wip